name: replay
description: Event Sourcing framework for Dart to build auditable apps with immutable events.
version: 1.0.0
repository: https://github.com/michasng/replay

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
