name: replay
description: An Event Sourcing framework for Dart.
version: 0.0.1
repository: https://github.com/michasng/replay

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
